### ISSUE TITLE
Does the plugin support windows phone?

### ISSUE THREAD

**Issue by mrtony** [infobip/push-plugin-cordova#3]
Does the plugin support windows phone?

**Comment by nmaric** [comment]
Hi Tony,

Currently, this plugin doesn't support Windows Phone.

**Comment by mrtony** [comment]
Is there any plan to support  Microsoft Push Notification Service (MPNS) in the future?

**Comment by nmaric** [comment]
We don't have an estimate for the Windows Phone yet. We have major requests for some core features on our backend as well as Android and iOS related changes, so WP is a bit lower on the priority list. We certainly must do it, but at the moment we have far more requests for Android and iOS, and unfortunately we have to prioritize certain things, so support for WP will certainly not come in next three months.

And for any further questions, don't hesitate to contact our [Push Support](mailto:push.support@infobip.com) or to ask them here. Thanks for your understanding.

**Comment by mrtony** [comment]
Hi Nikola:

Thanks for your information, Your plugin is really good to use and I'll keep watching the activity in github.

Tony
